name: Build and run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
  push:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed if using OIDC to get release secrets.

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet build tools
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0


      - name: Restore dotnet dependencies
        shell: bash
        id: restore
        run: dotnet restore

      - name: Build
        shell: bash
        id: build
        run: dotnet build

      - uses: launchdarkly/gh-actions/actions/verify-hello-app@verify-hello-app-v2.0.0
        with:
          use_server_key: true
          role_arn: ${{ vars.AWS_ROLE_ARN }}
          command:  dotnet run --project HelloOpenFeatureDotnet/HelloOpenFeatureDotnet.csproj --framework net8.0
